name = "ColdAtoms"
uuid = "a4a6137b-c86d-4c79-adc4-1660e24cdd31"
authors = ["Mikhail Goloshchapov"]
version = "0.1.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialPolynomials = "a25cea48-d430-424a-8ee7-0d3ad3742e9e"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
BenchmarkTools = "1.6.0"
Distributed = "1.11.0"
Distributions = "0.25.118"
HypergeometricFunctions = "0.3.28"
Interpolations = "0.15.1"
LinearAlgebra = "1.11.0"
MPI = "0.20.22"
OrderedCollections = "1.8.1"
OrdinaryDiffEq = "6.98.0"
PhysicalConstants = "0.2.4"
Plots = "1.40.17"
Polynomials = "4.0.19"
ProgressBars = "1.5.1"
QuantumOptics = "1.2.2"
Random = "1.11.0"
SpecialPolynomials = "0.5.0"
SplitApplyCombine = "1.2.3"
Unitful = "1.22.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
